ID_MAX_CHAR = 20
VALUE_MAX_CHAR = 50
V_SEPARATOR = ' | '
H_SEPARATOR = '='

SUBJECT_ID_COL_NAME = 'SUBJECT ID'
NAME_COL_NAME = 'NAME'

ASSISTANT_ID_COL_NAME = 'ASSISTANT ID'

COORDINATOR_ID_COL_NAME = 'COORDINATOR ID'